import { lazy } from 'react';

export const COMING_SOON_PATHS = [];

export const HomePage = lazy(() => import('../pages/HomePage'));
export const ShopPage = lazy(() => import('../pages/ShopPage'));
export const ProductDetailPage = lazy(() => import('../pages/ProductDetailPage'));
export const BuildPage = lazy(() => import('../pages/BuildPage'));
export const CollectionsPage = lazy(() => import('../pages/CollectionsPage'));
export const AboutPage = lazy(() => import('../pages/AboutPage'));
export const CartPage = lazy(() => import('../pages/CartPage'));
export const CheckoutPage = lazy(() => import('../pages/CheckoutPage'));
export const OrderConfirmationPage = lazy(() => import('../pages/OrderConfirmationPage'));
export const LoginPage = lazy(() => import('../pages/LoginPage'));
export const SignUpPage = lazy(() => import('../pages/SignUpPage'));
export const AccountPage = lazy(() => import('../pages/AccountPage'));
export const WishlistPage = lazy(() => import('../pages/WishlistPage'));
export const ConciergePage = lazy(() => import('../pages/ConciergePage'));
export const CorporatePage = lazy(() => import('../pages/CorporatePage'));
export const AdminPage = lazy(() => import('../pages/AdminPage'));
export const FaqPage = lazy(() => import('../pages/FaqPage'));
export const ShippingPage = lazy(() => import('../pages/ShippingPage'));
export const ContactPage = lazy(() => import('../pages/ContactPage'));
export const TrackOrderPage = lazy(() => import('../pages/TrackOrderPage'));
export const PrivacyPage = lazy(() => import('../pages/PrivacyPage'));
export const TermsPage = lazy(() => import('../pages/TermsPage'));
export const SearchPage = lazy(() => import('../pages/SearchPage'));
export const SupportPage = lazy(() => import('../pages/SupportPage'));
export const CareersPage = lazy(() => import('../pages/CareersPage'));
export const PressPage = lazy(() => import('../pages/PressPage'));
export const SustainabilityPage = lazy(() => import('../pages/SustainabilityPage'));
export const ComingSoonPage = lazy(() => import('../pages/ComingSoonPage'));
export const NotFoundPage = lazy(() => import('../pages/NotFoundPage'));
