/**
 * Resolve product image paths with optional WebP variants.
 * WebP files are generated by `npm run generate:webp` alongside JPEG sources.
 */
export function getWebpPath(imagePath) {
  if (!imagePath || !/\.jpe?g$/i.test(imagePath)) {
    return null;
  }
  return imagePath.replace(/\.jpe?g$/i, '.webp');
}

export function withPublicUrl(path, publicUrl = process.env.PUBLIC_URL || '') {
  if (!path) return '';
  if (path.startsWith('http') || path.startsWith('data:')) return path;
  const normalized = path.startsWith('/') ? path : `/${path}`;
  return `${publicUrl}${normalized}`.replace(/\/{2,}/g, '/').replace(':/', '://');
}

export function getProductImageSources(src, publicUrl = process.env.PUBLIC_URL || '') {
  const fallback = withPublicUrl(src, publicUrl);
  const webpPath = getWebpPath(src);
  const webp = webpPath ? withPublicUrl(webpPath, publicUrl) : null;

  return {
    fallback,
    webp,
    hasWebp: Boolean(webp),
  };
}
